POST http://localhost:3000/api/pacientes http/1.1
Content-Type: application/json

{
  "nombre": "Paciente 02",
  "habitacion": 2
}


###
PATCH http://localhost:3000/api/pacientes http/1.1
Content-Type: application/json

{
  "_id": "672e249fb52af1ec7947a735",
  "nombre": "Paciente 01",
  "habitacion": 12
}


###
DELETE http://localhost:3000/api/pacientes http/1.1
Content-Type: application/json

{
  "_id": "672e249fb52af1ec7947a735"
}